### ISSUE TITLE
not working, please help

### ISSUE THREAD

**Issue by hshehab** [Juniorn1003/Faitagram#1]
![screen shot 2017-12-24 at 4 56 06 pm](https://user-images.githubusercontent.com/33375002/34327047-8b934602-e8cb-11e7-9c3a-1d45b10aa371.png)

**Comment by Juniorn1003** [comment]
You have to install xmpp, install the requirements first.

**Comment by Juniorn1003** [comment]
Execute the setup.py then it will install it all.
