### ISSUE TITLE
Errooorr 111 

### ISSUE THREAD

**Issue by AlzMa** [Juniorn1003/Faitagram#10]
**Arrriiigth.**

Steps i was through that was not included in the tutorial:
-Install TOR: sudo apt-get install tor
-Install Selenium (Had the same PATH problem as the guy Xceed): found random youtubevideo that got the right codes to use in description. (It worked)

After that i started testing Instagram.
After 3 attemtps:
ERROR : ERRNO 111 Connection refused.
*tried "service tor start"* - didnt work

Last script was jumping IPS after 3 attempts. Perhaps you could change the script to jump ip after 2 attempts?

**Update**

Tested twitter aswell. Got same error after 3 tries.
Anyway. The script find the right password (within the 3 times). Tried to change password on a test account i got to second password in the wlist. It did find the right password and script stopped.

ALz

**Comment by Juniorn1003** [comment]
I would try to fix the problem.
When I was making the script, I had the same problem too.
It was from the tor service, while using STEM.
The error occurs when changing the IP, I will try to fix this problem.

**Comment by AlzMa** [comment]
Sweet! Update me!

**Comment by Juniorn1003** [comment]
Hmmm.... Did the service tor start did not really work?
Because I made a simple script showing the current IP using stem,
but it showed errno111 when tor was not running, and it was fully functioning when I did "service tor start"....

**Comment by AlzMa** [comment]
Did type it, Perhaps it didnt work?
Well i did install Tor (you didnt include the code in the guide..) 
Then i tried «service Tor start» didnt work :s

**Comment by Juniorn1003** [comment]
Then did it just said error [Errno 111] or was there a long error before that?

**Comment by AlzMa** [comment]
Did say [Errno 111]

**Comment by AlzMa** [comment]
Connection reduser something..

**Comment by AlzMa** [comment]
Very short, red text, Connection refused*, Errno 111

**Comment by 5N00PD063** [comment]
same error...

we need to get the proxy working

**Comment by Juniorn1003** [comment]
Happy New Year!
Please just wait about a week, I would try to fix the majority of the issues.

**Comment by AlzMa** [comment]
Happy New Year!
Take your time! Feel free to Update me/us on your way! Looking forward to get down some inactive accounts.. whitehattedman

**Comment by Juniorn1003** [comment]
wow your fast

**Comment by AlzMa** [comment]
;-)

**Comment by 5N00PD063** [comment]
Happy New Year to you good Sirs!

**Comment by karmaholic** [comment]
do i need to use tor to bruteforce?

**Comment by Juniorn1003** [comment]
@karmaholic Yes, otherwise the account will get locked.

**Comment by Juniorn1003** [comment]
@karmaholic Any kind of proxy, not just only tor.

**Comment by karmaholic** [comment]
okay so how would i make tor my machine that it bruteforces through and also it always says to me unable to locate libbsl-dev and firefoxdriver any help would be appreciated

**Comment by Juniorn1003** [comment]
@karmaholic You have to execute the setup.py, because that will install the dependencies in the right place.

**Comment by AlzMa** [comment]
Any Progress?

**Comment by Juniorn1003** [comment]
I updated faitagram && setup.py, clone it again and execute it again.
Let me know if it works so I can close the issue.

**Comment by AlzMa** [comment]
- Checking Username Existence -

Traceback (most recent call last):
  File "faitagram", line 339, in <module>
    main()
  File "faitagram", line 101, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 155, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 177, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 2

I can open a new thread if you want. But new error code.. *yey*

**Comment by Juniorn1003** [comment]
Hahaha.... You were WAY too early... I just changed the setup.py.
It will install the compatible version of gekodriver, Please do it again....

**Comment by Juniorn1003** [comment]
Wait wait wait dont clone it yet
I found a another error

**Comment by Juniorn1003** [comment]
Now it's okay.

**Comment by AlzMa** [comment]
hahah you sneak!

**Comment by AlzMa** [comment]
Im gonna close this thread now. It actually wooorkzz
goodjob dawg

**Comment by AlzMa** [comment]
I regret! 

If finds the wrong password :P

**Comment by AlzMa** [comment]
Tested same username again: found new password after 1 try. Wrong password guess again :(

**Comment by AlzMa** [comment]
Third attepmt on same username; script froze..

**Comment by Juniorn1003** [comment]
Humph. This is the proxy problem again...
The site disabled the login page.....

**Comment by AlzMa** [comment]
Hmm :/

**Comment by AlzMa** [comment]
Will you be able to solve it you think? Mr.Legend? <3

**Comment by Juniorn1003** [comment]
Yes

**Comment by Juniorn1003** [comment]
By the way, if you want to see the script bruteforcing the web with your own eyes, you can uncomment
the line         
display = Display(visible=0, size=(800, 600))
and
display.start()
by putting a # in front of it.

**Comment by AlzMa** [comment]
Hit me up when you have fixed the proxy problemo B-) Lookin forward to it

**Comment by karmaholic** [comment]
can someone tell me what to do from the start im lost

**Comment by AlzMa** [comment]
@karmaholic , Lol. :p

The script does not work at the moment. 

When Its working the guide on wonderhowto will work just fine :D

**Comment by Juniorn1003** [comment]
Hey @AlzMa and @karmaholic, the errno 111 issue is fixed so can I close this issue and we move to hshehab's issue? By the way, I am currently real close to finishing, just need to put few lines and done.

**Comment by AlzMa** [comment]
Good work. No problemo!
