### ISSUE TITLE
Error setup.py

### ISSUE THREAD

**Issue by tiansyahisal** [Juniorn1003/Faitagram#109]
when i wrote pythone setup.py, there is error massage 
File "setup.py", line 42
 chmod +x faitagram && chmod +x setup.py
SyntaxError: invalid syntax
 
pls help meeee sirr

**Comment by elliotalderson56** [comment]
Dis you ever figure out a solution? I'm having the same issue

**Comment by SimplePotato** [comment]
Same here

**Comment by daniel071** [comment]
The issue is that line 42 is bash but it is written in python. Simply deleting that line will solve the issue. Pull requests #114 and #113 have done that. For more detail you can see #116 , https://github.com/Juniorn1003/Faitagram/issues/116#issuecomment-490084822
