### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by sachin-acharya-practice** [Juniorn1003/Faitagram#126]
Every time I run comand "python setup.py" or "sudo python setup.py" or "sudo python3 setup.py" or "python3 setup.py" or "python3 setup.py install" or "sudo python3 setup.py install" 
it shows the errorlike

  File "setup.py", line 42
    chmod +x faitagram && chmod +x setup.py
                     ^
SyntaxError: invalid syntax

**Comment by parzivalandmerlin** [comment]
This script will not run anymore. but for this you have to go into the setup.py file then change
chmod +x faitagram && chmod +x setup.py 
to
os.system("chmod +x faitagram && chmod +x setup.py")

**Comment by analjesus** [comment]
> 
> 
> This script will not run anymore. but for this you have to go into the setup.py file then change
> chmod +x faitagram && chmod +x setup.py
> to
> os.system("chmod +x faitagram && chmod +x setup.py")

What do you mean the script will not run anymore? I have it running, albeit unreliably.

**Comment by parzivalandmerlin** [comment]
I guess I meant they aren’t updating it anymore. I could never get it to connect when running it.
