### ISSUE TITLE
Why?Can't I try it anymore?

### ISSUE THREAD

**Issue by ratul3123** [Juniorn1003/Faitagram#136]
Doesn't it really work? Actually I am searching for such a tool like this. Is there anything like **_Faitagram_**? **Please inform me**. Can't I try this tool for once? I wanna try to see if it really works or not. It will be really a pleasure to me if I find such a tool.

**Comment by RootHuayra** [comment]
A lot of Instagram Bruteforce Tools have been patched because instagram doesn't pass the "Password" in the ajax request, they only pass the "Username" and "Encrypted Password"

**Comment by ratul3123** [comment]
Well. Would you like to suggest me some tools please?

**Comment by mmabd** [comment]
> Well. Would you like to suggest me some tools please?

+1
