### ISSUE TITLE
chmod +x faitagram SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by TheLime1** [Juniorn1003/Faitagram#142]
lime@kali:~/Faitagram$ python3 setup.py
  File "/home/lime/Faitagram/setup.py", line 42
    chmod +x faitagram && chmod +x setup.py
                    ^
SyntaxError: invalid syntax

i running on kali linux

**Comment by TwixXEpic** [comment]
SyntaxError: invalid syntax

What am i going to do help me plz :D
