### ISSUE TITLE
Unicode and strings?

### ISSUE THREAD

**Issue by PlaguedByWeirdness** [Juniorn1003/Faitagram#16]
Dammit, almost worked

Now I get:

Traceback (most recent call last):
File "faitagram", line 277, in
main()
File "faitagram", line 44, in main
if os.path.exists(wordlist) == False:
File "/usr/lib/python2.7/genericpath.py", line 26, in exists
os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Is there any unicode method that's returning a field that is not entered?

**Comment by Juniorn1003** [comment]
No, there is none.... Let me try to fix this problem.

**Comment by Juniorn1003** [comment]
Try again! Updated the script, comes with more speed.

**Comment by Juniorn1003** [comment]
If it happens again, let me know by putting a another issue.
