### ISSUE TITLE
IndentationError. Changing public IP

### ISSUE THREAD

**Issue by AlzMa** [Juniorn1003/Faitagram#17]
File "faitagram", line 99
    def setIP(self):    # Changing Public IP 
                                            ^
IndentationError: unindent does not match any outer indentation level

Did i miss out anything or..

**Comment by PlaguedByWeirdness** [comment]
I fixed that with adding extra space before def setIP, then you will have to add 2 spaces before def execute, something like that, but then new error appears, check my issue for that one

**Comment by AlzMa** [comment]
hmm

**Comment by AlzMa** [comment]
File "faitagram", line 163
    def webBruteforce(self, username, wordlist, service, delay):
                                                               ^
IndentationError: unindent does not match any outer indentation level

**Comment by PlaguedByWeirdness** [comment]
Every def in class Bruter should be 4 spaces from the start of the line

**Comment by AlzMa** [comment]
Thanks, ill check.!

**Comment by AlzMa** [comment]
Error : local variable 'my_ip' referenced before assignment .. next error..

**Comment by PlaguedByWeirdness** [comment]
Oh, I get the one that I submitted on the other issue, not that one, well I guess we'll just have to wait

**Comment by AlzMa** [comment]
@PlaguedByWeirdness ah, that sucks..

**Comment by PlaguedByWeirdness** [comment]
Yeah :/
Never quite used Python myself, used lots of C/C++ though

**Comment by AlzMa** [comment]
:( Thanks for your help tho. :D

**Comment by Juniorn1003** [comment]
Haha never new Plague will help : )
