### ISSUE TITLE
my_ip refrenced before assignment error

### ISSUE THREAD

**Issue by AlzMa** [Juniorn1003/Faitagram#18]
Error : local variable 'my_ip' referenced before assignment

thats the code. Whats the issue(Questionmark)

**Comment by Juniorn1003** [comment]
Sorry, was testing something for the proxy, just wait a minute, will fix it.

**Comment by smokeabird** [comment]
for fixing it, i put at the end of the "def webBruteforce" a call of self.setIP() an initialization of my_ip with the call of ip.42.pl, just before j=0 :

        j=0
	self.setIP()
        my_ip = urlopen("http://ip.42.pl/raw").read()
	
I don't know if self.setIP is necessary but it works.

what do you think about it ?

**Comment by Juniorn1003** [comment]
@smokeabird  the self.setIP() is for changing the Public IP, so the security can not catch you.

**Comment by AlzMa** [comment]
Alright, i don't like messing with the script. I don't really know what i do too well.. so i thought iwill just wait for @Juniorn1003 to solve it. 

Tried to put in some global words here and there.. but then my pc crashed when i ran the script. So from now on i will wait.. :p

**Comment by Juniorn1003** [comment]
@AlzMa You can come out from the nutshell now, I updated the script, it will also have more speed, but the proxy problem is still not solved yet.

**Comment by Juniorn1003** [comment]
I think this problem is solved so I will close this issue.
