### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bedoe** [Juniorn1003/Faitagram#2]
Well I think you remember me...  brut3k1t didn't work and I saw your comment to download faitagram.. I downloaded but it doesn't work too
![hh](https://user-images.githubusercontent.com/34168917/34328532-fcaa8780-e8f1-11e7-8cbf-badb45c363a1.png)
any help???

**Comment by Juniorn1003** [comment]
You have to install selenium. First run setup.py first.

**Comment by Juniorn1003** [comment]
If you want to do it manually, type :

pip install -U selenium

in the terminal.
