### ISSUE TITLE
pb with tor cookie

### ISSUE THREAD

**Issue by trashforce** [Juniorn1003/Faitagram#20]
[ ok ] Restarting tor (via systemctl): tor.service.
Please Enter The NAME Of The Facebook Account : jjj
[ ok ] Checking Account Existence

"We were unable to read tor's authentication cookie...

  Path: /var/run/tor/control.authcookie
  Issue: Authentication failed: unable to read '/var/run/tor/control.authcookie' ([Errno 13] Permission denied: u'/var/run/tor/control.authcookie')
sh: 1: service: not found"

**Comment by Juniorn1003** [comment]
Are you sure your torrc configuration is ok?

**Comment by Juniorn1003** [comment]
If it is ok and if it still happens, then I will have to fix this.

**Comment by trashforce** [comment]
when i use tor bundle, it works well

**Comment by Juniorn1003** [comment]
No, I meant is the torrc configuration good?
It is in /etc/tor/torrc,
and the cookie authentication, controlport 9051 and tor control hashed password should be uncommented.
Run setup.py, it will do it automatically for you.

**Comment by trashforce** [comment]
you're right, 👍 
i got a pb of permissions with geckodriver :
"geckodriver 
mv : voulez-vous remplacer '/usr/local/bin/geckodriver' en outrepassant le mode 0775 (rwxrwxr-x) ? y
mv: impossible de déplacer 'geckodriver' vers '/usr/local/bin/geckodriver': Permission non accordée"

and a pb of opening with the torrc2 because it doesn't exists : 
"fx = open("/etc/tor/torrc2","w+")
IOError: [Errno 13] Permission denied: '/etc/tor/torrc2"

**Comment by Juniorn1003** [comment]
Alors, le problème est-il résolu maintenant?

**Comment by trashforce** [comment]
je t'avoue que je n'arrive pas à le resoudre pour le moment :  pb de permission que j'essaie d'eradiquer en faisant un purge de tor et en reinstallant le setup.py mais il bloque toujours sur le remplacement ou le deplacement de geckodriver !!! mais je vais trouver !!!!
