### ISSUE TITLE
File "faitagram", line 97

### ISSUE THREAD

**Issue by gtsoph** [Juniorn1003/Faitagram#21]
root@kali:~/Faitagram# python faitagram -s instagram -u username -w 
/root/Downloads/10_million_password_list_top_1000000.txt.icloud
  File "faitagram", line 97
    def setIP(self):    # Changing Public IP 

IndentationError: unindent does not match any outer indentation level

**Comment by Juniorn1003** [comment]
You could have easily fixed that. By the way, issue fixed.

**Comment by dwisiswant0** [comment]
What solution?

**Comment by dwisiswant0** [comment]
Gak jelas. Solusi belum ada udah diclosed. Kntl.

**Comment by Juniorn1003** [comment]
@dwisiswant0 The issue is fixed, and it was just an indentation error. It was just a typo in the script.
Masalahnya tetap, dan itu hanya kesalahan indentasi. Itu hanya salah ketik dalam naskahnya.
