### ISSUE TITLE
Error: Traceback (most recent call last):

### ISSUE THREAD

**Issue by MelissaMV** [Juniorn1003/Faitagram#24]
@Juniorn1003 Heyyy how do I solve this error?

I'm using Kali Linux

I installed Selenium

I have Geckodriver in /usr/bin/geckodriver

But I'm still getting this error:

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 299, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 131, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 148, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

I edited line 148 and still got this error:

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 299, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 131, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 148, in usercheck
    driver = webdriver.Firefox(executable_path="/usr/bin/geckodriver")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

What else needs to be done?

**Comment by Juniorn1003** [comment]
Are you sure Geckodriver is in /usr/local/bin?

**Comment by Juniorn1003** [comment]
Or it just may be the version problem, (Selenium 3.40 + Geckodriver 0.16.0 + Firefox 53.0) Works Ok, under that firefox will not function properly.

**Comment by MelissaMV** [comment]
I have two versions of Firefox in Kali Linux - The version that came with Kali Linux and the the latest version I manually installed. Should I remove the old Kali Linux version of Firefox? I also have updated versions of Selenium and Geckodriver 0.18..0

**Comment by vanguard71** [comment]
MelissaMv,
   Looking at your error output, it looks selinium looking for geckodriver in /usr/bin.   You probably installed it in /usr/local/bin.   I guess you can just create a symlink to solve the problem 

Solution 1:
su -
ln -s /usr/local/bin/geckodriver /usr/bin/geckodriver


solution 2:
Also, do you have the latest code for faitagrafm; because Justin is calling 

driver = webdriver.Firefox()

your local version appears to be calling as

driver = webdriver.Firefox(executable_path="/usr/bin/geckodriver")

You can update code by doing

git pull 

in your local repository

**Comment by Juniorn1003** [comment]
I think this problem is solved, according to selenium issues #3884, ( https://github.com/SeleniumHQ/selenium/issues/3884 ) It was just about the version of the geckodriver. I changed the geckodriver v.13 install to v.19 latest. So it will work now.

**Comment by vanguard71** [comment]
what is the most recent error?

**Comment by MelissaMV** [comment]
Heyy @vanguard71 this is the error i'm getting with or without the added script: driver = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver")

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 299, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 131, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 148, in usercheck
    driver = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

root@kali:~/Desktop/Faitagram#

**Comment by Juniorn1003** [comment]
@MelissaMV According to selenium issue https://github.com/SeleniumHQ/selenium/issues/3884 , this is an issue of the version.... Are you sure you have the correct version?

**Comment by vanguard71** [comment]
try to output and ensure you are running right version with following 

import selenium
print selenium.__version__

Also, following line is incorrect.  You want the directory; not the full path of executable

webdriver.Firefox(executable_path="/usr/local/bin/geckodriver")

you want

webdriver.Firefox(executable_path="/usr/local/bin/")


BTW, do not share your password in the forum and public media when you are putting exception details.   you should change that phrase.  

[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C

**Comment by Juniorn1003** [comment]
@vanguard71  Thanks for your correction. And also, the hashed password is okay to share, since it is not that important, and you can change it easily and generate a new one easily.

**Comment by MelissaMV** [comment]
@Juniorn1003 @vanguard71 these are the versions I'm using:

root@kali:~# python -c "import selenium; print(selenium.__version__)"
3.8.1

root@kali:~# geckodriver
1516239285388	geckodriver	INFO	geckodriver 0.19.0
1516239285455	geckodriver	INFO	Listening on 127.0.0.1:4444

@Juniorn1003 setup.py is configured to install Geckodriver 64 Bit: "geckodriver-v0.19.0-linux64.tar.gz" but some folks still has a 32 Bit Operating system - I suggest you revert to the original script and let folks manually install Geckodriver 32 Bit or 64 Bit.

**Comment by MelissaMV** [comment]
For some reason its executing tonight, i'm getting this error:

root@kali:~/Desktop/Faitagram# ls
faitagram  LICENSE  README.md  setup.py  wlist

root@kali:~/Desktop/Faitagram# python faitagram -h
Traceback (most recent call last):
  File "faitagram", line 25, in <module>
    controller = Controller.from_port(port=9051)
  File "/usr/local/lib/python2.7/dist-packages/stem/control.py", line 1026, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 376, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 247, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 405, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused
root@kali:~/Desktop/Faitagram#

**Comment by vanguard71** [comment]
netstat -nltp 

Is anything running on 9051

**Comment by SpartanKing4** [comment]
I have the same Errno 111 issue !
@vanguard71 I’ve checked and I have nothing on 9051 , what should I do to fix it ?

**Comment by SpartanKing4** [comment]
Have you tried restarting tor ? 

Just use /etc/init.d/tor restart , it worked for me 

Though I’m still getting an error ( I’m going to make an issue soon)

**Comment by MelissaMV** [comment]
@vanguard71 nope nothings running on 9051
@SpartanKing4 thx for the tip - i restarted tor but same error.

**Comment by Juniorn1003** [comment]
Oh, Thats the proxy problem.

**Comment by Juniorn1003** [comment]
script updated. This script will go until you encounter the proxy problem.

**Comment by Juniorn1003** [comment]
Also Added a function that makes the setup.py calculate the OS bit, and installs the right geckodriver.

**Comment by Juniorn1003** [comment]
I think this problem is fixed.
