### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TheMathGenuisGirl1103** [Juniorn1003/Faitagram#26]
How come I keep getting Syntax Error file faitagram line 260???

**Comment by trashforce** [comment]
modify like this : format(username,password))

a parenthesis forgotten

**Comment by Juniorn1003** [comment]
@trashforce  Thanks!

**Comment by TheMathGenuisGirl1103** [comment]
do you want me to edit that in the file?

**Comment by Juniorn1003** [comment]
Nah, fixed right away
