### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by maumau35** [Juniorn1003/Faitagram#30]
think there is something wrong with geckodriver
[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 299, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 131, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 148, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

geckodriver.log

                                                                                                   

1516175356446   geckodriver     INFO    geckodriver 0.19.0
1516175356454   geckodriver     INFO    Listening on 127.0.0.1:33687
1516175357458   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.ZfVWIuzDFEmE"
1516175360965   Marionette      ERROR   Error on starting server: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 95"  data: no]
[Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 95"  data: no]
MarionetteServer.prototype.start@chrome://marionette/content/server.js:95:19
MarionetteComponent.prototype.init@resource://gre/components/marionette.js:217:5
MarionetteComponent.prototype.handle@resource://gre/components/marionette.js:112:5

**Comment by Juniorn1003** [comment]
put : executable_path="/usr/local/bin/geckodriver"
in the parameters in driver = Firefox()

**Comment by Juniorn1003** [comment]
I've done that for you.

**Comment by maumau35** [comment]
Thank you for doing this
