### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by vivekmittal1999** [Juniorn1003/Faitagram#35]
sh: 1: /etc/init.d/tor: not found
Traceback (most recent call last):
  File "faitagram", line 295, in <module>
    main()
  File "faitagram", line 68, in main
    with open('/etc/tor/torrc','r') as f:
IOError: [Errno 2] No such file or directory: '/etc/tor/torrc'

**Comment by Juniorn1003** [comment]
It is because you are not using Kali linux.
