### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by vivekmittal1999** [Juniorn1003/Faitagram#36]
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    fp = open("/etc/tor/torrc")

**Comment by Juniorn1003** [comment]
Can You PLEASE give me the full error code?

**Comment by Juniorn1003** [comment]
No response, closing.

**Comment by vivekmittal1999** [comment]
Wait I was ill yesterday so that's why can't get to u. Wait I am sending it
now
