### ISSUE TITLE
Help with setup.py

### ISSUE THREAD

**Issue by Baconator7107** [Juniorn1003/Faitagram#4]
When I try to chmod faitagram and enter "chmod +x faitagram && chmod +x setup.py"
I get chmod: cannot access 'setup.py' :No such file or directory.

**Comment by Juniorn1003** [comment]
Never knew my null byte readers will come this far.
If you want to chmod the FOLDER then get OUT of the file, then type : chmod -R 755 Faitagram

If you want to chmod the FILES, then do the "chmod +x faitagram && chmod +x setup.py" AFTER you go in the folder.
