### ISSUE TITLE
help......

### ISSUE THREAD

**Issue by apu745** [Juniorn1003/Faitagram#48]
[ ok ] Restarting tor (via systemctl): tor.service.
Traceback (most recent call last):
  File "faitagram", line 267, in <module>
    main()
  File "faitagram", line 69, in main
    data = contents[59]
IndexError: list index out of range

**Comment by Juniorn1003** [comment]
It's because you do not have torrc. I will solve this problem shortly.

**Comment by Juniorn1003** [comment]
Problemo fixed. Thanks for using the script!
