### ISSUE TITLE
Cannot access geckodriver

### ISSUE THREAD

**Issue by clifffischer** [Juniorn1003/Faitagram#49]
Have selenium and tor butonce i rum python setup.py in script i geterrors regarding geckodriver

**Comment by clifffischer** [comment]
This tried to remove and install an old geckodriver version but I’ve already extracted the new one to my computer

**Comment by Juniorn1003** [comment]
The program installs the right geckodriver by looking at your firefox version, since some are not compatible.

**Comment by Juniorn1003** [comment]
So please just use the one setup.py installs.
