### ISSUE TITLE
Please Help  (Geckodriver)

### ISSUE THREAD

**Issue by Krypt8** [Juniorn1003/Faitagram#56]
root@kali:~/Faitagram# python setup.py
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 224 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tor is already the newest version (0.3.2.10-1).
0 upgraded, 0 newly installed, 0 to remove and 224 not upgraded.
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: Pysocks in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python2.7/dist-packages (from pyvirtualdisplay)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xvfb is already the newest version (2:1.19.6-1).
0 upgraded, 0 newly installed, 0 to remove and 224 not upgraded.

 
 32.0 
 

--2018-03-12 20:14:03--  https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux32.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-12 20:14:04 ERROR 404: Not Found.

tar (child): geckodriver-v0.16.1-linux32.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'geckodriver-v0.16.1-linux32.tar.gz': No such file or directory
chmod: cannot access 'geckodriver': No such file or directory
mv: cannot stat 'geckodriver': No such file or directory

**Comment by Juniorn1003** [comment]
Fixed.
