### ISSUE TITLE
Can’t run script due to Selenium not finding firefox

### ISSUE THREAD

**Issue by clifffischer** [Juniorn1003/Faitagram#58]
Firefox-ESR is what i have installed and Selenium won’t run that in the script. I try to apt-get install firefox and i get error package has no installation candidate. Is there a way i can change the script to get it to pull from firefox esr or use another Selenium version that maybe supports firefox esr?

**Comment by Juniorn1003** [comment]
Try to find a another selenium version or try to install the newest firefox.
