### ISSUE TITLE
General SOCKS server failure

### ISSUE THREAD

**Issue by SebsSR** [Juniorn1003/Faitagram#65]
After starting bruteforce it tries 1 password and then error : 0x01 General SOCKS server failure

**Comment by alexandru044** [comment]
I got the same problem....

**Comment by WillBowen28** [comment]
yep same here

**Comment by Jashan01** [comment]
same here

**Comment by mysamvv** [comment]
same here

**Comment by PabloGamerYTB** [comment]
No Solution ?

**Comment by Palmus84** [comment]
Still got same...
