### ISSUE TITLE
Errno 8 error

### ISSUE THREAD

**Issue by dabslabcab** [Juniorn1003/Faitagram#66]
when I ran the Instagram command it started loading and then I got an errno 8 error. I have a screenshot of everything running here. Any help would be appreciated.
![oofy](https://user-images.githubusercontent.com/38023706/38225431-21bcb1d4-36b2-11e8-88e4-df7b8cc43960.PNG)

**Comment by abkreno2530** [comment]
my to have this error i dont know what i do

**Comment by abkreno2530** [comment]
any one help us pleas

**Comment by ggold729** [comment]
This is my current problem too
