### ISSUE TITLE
problem with Setup.py

### ISSUE THREAD

**Issue by felashleges** [Juniorn1003/Faitagram#67]
I get this message constantly when running setup.py:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
The following packages were automatically installed and are no longer required:
  libgcr-3-common libjsoncpp1 libtxc-dxtn-s2tc libxfont1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tor is already the newest version (0.3.2.10-1).
The following packages were automatically installed and are no longer required:
  libgcr-3-common libjsoncpp1 libtxc-dxtn-s2tc libxfont1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: Pysocks in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python2.7/dist-packages (from pyvirtualdisplay)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xvfb is already the newest version (2:1.19.6-1).
The following packages were automatically installed and are no longer required:
  libgcr-3-common libjsoncpp1 libtxc-dxtn-s2tc libxfont1
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.

 
 32.0 
 

sh: 1: firefox: not found
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    version  = result[marker:].splitlines()[0]     # spliting the output, the version is something like aa.bb.cc
IndexError: list index out of range

____
I got firefox 59.0.2. installed manually, I deleted the prev. version (52.x.x.) What should I do?
Thanks you for helping!
Have a nice day!

**Comment by Juniorn1003** [comment]
You can delete that line, it doesn’t matter.
