### ISSUE TITLE
Termux Error

### ISSUE THREAD

**Issue by azi0uez** [Juniorn1003/Faitagram#75]
Hi , I'm glad to see that your work is getting better but Unfortunately there is an error when I try to install requirements : "python setup.py" 
it says : Traceback ( most recent calll kast ) :
 File "setup.py",line3 , in <module>
     OS_bit = ( round(math.log(sys.maxint,2)+1))    "get the bit
AttributeError ;module 'sys' has no attribute 'maxint'

Can you please help me ?

**Comment by Zerocchi** [comment]
If you are using Python 3 as default (which is probably the case), try running it using Python 2. `sys.maxint` is only available in Python 2 as it is replaced by `sys.maxsize` in Python 3.
