### ISSUE TITLE
Bug Report on win10

### ISSUE THREAD

**Issue by HuhMe9** [Juniorn1003/Faitagram#80]
C:\Users\HP\Desktop\Faitagram-master>python setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    OS_bit = (round(math.log(sys.maxint,2)+1))  # get the bit
AttributeError: module 'sys' has no attribute 'maxint'

**Comment by didotb** [comment]
I tried chmod 777 the setup.py before executing it with python to be sure.
I had same issues back then with different python codes, and it seems to fix itself when I chmod those files
