### ISSUE TITLE
cannot access 'faitagram'

### ISSUE THREAD

**Issue by pepperochini** [Juniorn1003/Faitagram#84]
when i enter the command "chmod +x faitagram && chmod +x setup.py" i am returned with "chmod: cannot access 'faitagram': No such file or directory"

I feel like am i missing something?

**Comment by memreaksan** [comment]
Try to change directory to Faitagram using "cd Faitagram"

**Comment by pepperochini** [comment]
im still returned with 
bash: cd: faitagram: No such file or directory

**Comment by pepperochini** [comment]
im still returned with
bash: cd: faitagram: No such file or directory

**Comment by pepperochini** [comment]
i got it by changing the correctly changing the directory as memreaksan described. thanks so much
