### ISSUE TITLE
Python isn't working in Terminal or is it me?

### ISSUE THREAD

**Issue by mzsherman** [Juniorn1003/Faitagram#89]
I keep getting this when I run python setup.py--

sudo: apt-get: command not found
sh: pip: command not found
sh: pip: command not found
sh: pip: command not found

64.0

sh: firefox: command not found
Traceback (most recent call last):
File "setup.py", line 16, in
version = result[marker:].splitlines()[0] # spliting the output, the version is something like aa.bb.cc
IndexError: list index out of range

What am I doing wrong?

**Comment by Juniorn1003** [comment]
Use kali linux
