### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mahammmm** [Juniorn1003/Faitagram#94]
After cloning faitagram when u type "is" to open it is shows no command "is" found

**Comment by Juniorn1003** [comment]
It's not i, it's l

**Comment by mahammmm** [comment]
Sir can u please help me hacking an insta account?

**Comment by mahammmm** [comment]
I assure u.. There is no bad intenstion
Its just about my future...
By getting his id hacked.. I will get to know what he is not ready to tell..
Please sir.. Pls...! 🙏
